// import './bootstrap';
import './webfont';
import './menu';
import './table';
import './table-pagination';
import './table-filter';
import './form';
import './form-validation';
import './tabs';
import './modal-destroy';
import './notification';
import './dropdown';